name: prompting_client
description: Dart client for the AppArmor prompting gRPC service.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  freezed_annotation: 3.1.0
  grpc: ^4.0.0
  json_annotation: ^4.9.0
  protobuf: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.24.0
  ubuntu_lints: ^0.4.1
