name: aa-prompting-test
base: core22
version: "0.1"
summary: A simple helper for testing out apparmor prompting
description: |
  Just a wrapper around a handful of commands to help with testing the
  interactions between snapd and an apparmor-prompting client without
  needing to do everything manually.
grade: devel
confinement: strict

parts:
  scripts:
    plugin: dump
    source: scripts/
    stage-packages:
      - v4l-utils
      - alsa-utils

apps:
  read:
    command: ./read.sh
    plugs:
      - home
  create:
    command: ./create.sh
    plugs:
      - home
  create-single:
    command: ./create-single.sh
    plugs:
      - home

  camera:
    command: ./camera.sh
    plugs:
      - camera

  microphone:
    command: ./microphone.sh
    plugs:
      - audio-playback
      - audio-record

# This is a workaround to access alsa config https://github.com/canonical/checkbox/issues/273
layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
