name: apparmor-prompting
base: core22
version: '0.1'
summary: A simple apparmor prompting client
description: |
  An initial apparmor prompting client to support internal user testing
  and iteration on the UI.
grade: devel
confinement: strict

apps:
  apparmor-prompting:
    command: bin/aa-prompt-client
    extensions: [gnome]
    plugs:
      - snap-prompting-control
      - home

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.22.2
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  client:
    plugin: rust
    source: aa-prompt-client

  ui:
    after: [flutter-git]
    source: apparmor_prompt
    plugin: nil
    override-build: |
      set -e
      dart run build_runner build
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
