name: prompting-client
base: core24
version: git
title: Prompting Client
summary: Prompting Client
description: The prompting user interface for snap apparmor prompting
source-code: https://github.com/canonical/prompting-client.git
issues: https://github.com/canonical/prompting-client/issues
license: GPL-3.0
grade: stable
confinement: strict

apps:
  scripted:
    command: bin/prompting-client-scripted
    extensions: [gnome]
    environment: &env
      PROMPTING_CLIENT_SOCKET: "${XDG_RUNTIME_DIR}/prompting.sock"
    plugs: &plugs
      - home
      - snap-interfaces-requests-control

  echo:
    command: bin/prompting-client-echo
    extensions: [gnome]
    environment: *env
    plugs: *plugs

  daemon:
    command: bin/prompting-client-daemon
    desktop: usr/share/applications/prompting-client-daemon.desktop
    extensions: [gnome]
    environment: *env
    plugs: *plugs
    daemon: simple
    passthrough: # TODO: Remove once daemon-scope lands in snapcraft
      daemon-scope: user
    restart-condition: on-success
    restart-delay: 2s

  # Doesn't need access to home or snapd
  logging-level:
    command: bin/prompting-client-set-log-level
    extensions: [gnome]
    environment: *env

plugs:
  snap-interfaces-requests-control:
    handler-service: daemon

parts:
  fvm:
    plugin: nil
    source: scripts/fvm
    override-build: |
      bash $CRAFT_PART_SRC/install.sh
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  prompting-client:
    plugin: rust
    source: prompting-client
    override-build: |
      set -e
      mkdir -p $(dirname $CRAFT_PART_SRC)/protos
      cp $CRAFT_PROJECT_DIR/protos/* $(dirname $CRAFT_PART_SRC)/protos/
      craftctl default
    build-packages:
      - libssl-dev
      - pkg-config
    build-snaps:
      - protobuf

  prompting-client-ui:
    after: [fvm]
    source: .
    plugin: nil
    override-build: |
      set -eux
      fvm install
      fvm dart pub global activate melos
      fvm dart pub global run melos clean
      fvm dart pub global run melos bootstrap
      fvm dart pub global run melos generate

      cd flutter_packages/prompting_client_ui
      fvm flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

  desktop-files:
    plugin: dump
    source: .
    organize:
      snap/gui/prompting-client.desktop: usr/share/applications/prompting-client-daemon.desktop
