name: Code Checks

on:
    pull_request:
    push:
        branches: [main]

jobs:
    prek:
        runs-on: ubuntu-24.04
        steps:
            - uses: canonical/desktop-engineering/gh-actions/flutter/setup@e1069c189573b3525a60f54c5107ea3264f80805
            - run: melos generate

            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  components: clippy, rustfmt

            - name: Install dependencies
              run: |
                  sudo apt-get -y update
                  sudo apt-get -y install protobuf-compiler

            - uses: j178/prek-action@v2
