name: Code Checks

on:
    pull_request:
    push:
        branches: [main]

jobs:
    prek:
        runs-on: ubuntu-26.04
        steps:
            - uses: canonical/desktop-engineering/gh-actions/flutter/setup@f45615b7e809a5dac2c6f24cbca7cafe67df9831
            - run: melos generate

            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  components: clippy, rustfmt

            - name: Install dependencies
              run: |
                  sudo apt-get -y update
                  sudo apt-get -y install protobuf-compiler

            - uses: j178/prek-action@v3.0.0
