name: Code Checks

on:
    pull_request:
    push:
        branches: [main]

jobs:
    prek:
        runs-on: ubuntu-latest
        steps:
            - uses: canonical/desktop-engineering/gh-actions/flutter/setup@2db611c684665808acf24723ea8fc6d2050f5f99
            - run: melos generate

            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  components: clippy, rustfmt

            - name: Install dependencies
              run: |
                  sudo apt-get -y update
                  sudo apt-get -y install protobuf-compiler

            - uses: j178/prek-action@v2
