name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v3
      - run: melos generate
      - run: melos gen-l10n
      - uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated

  l10n:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v3
      - run: melos gen-l10n
      - name: Check for outdated l10n
        if: github.event_name == 'pull_request'
        run: ./scripts/check-outdated-files.sh
      - name: Create PR
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: "**/l10n/*.dart"
          title: "chore: regenerate l10n"
          commit-message: "chore: regenerate l10n"
          branch: create-pull-request/l10n
          delete-branch: true

  test:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
          restore-keys: |
            ${{ runner.os }}-repo-
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v3
      - run: sudo apt update && sudo apt install -y lcov
      - run: melos coverage
      - uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  prompting-client-ui:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
          restore-keys: |
            ${{ runner.os }}-repo-
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang cmake libglib2.0-dev libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb
      - name: Run integration tests
        working-directory: flutter/apps/prompting_client_ui
        run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test
