name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  l10n:
    runs-on: ubuntu-24.04
    steps:
      - uses: canonical/desktop-engineering/gh-actions/flutter/setup@e1069c189573b3525a60f54c5107ea3264f80805
      - run: melos generate
      - run: melos gen-l10n
      - name: Check for outdated l10n
        if: github.event_name == 'pull_request'
        run: ./scripts/check-outdated-files.sh
      - name: Create PR
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: "**/l10n/*.dart"
          title: "chore: regenerate l10n"
          commit-message: "chore: regenerate l10n"
          branch: create-pull-request/l10n
          delete-branch: true

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: canonical/desktop-engineering/gh-actions/flutter/setup@e1069c189573b3525a60f54c5107ea3264f80805
      - run: sudo apt update && sudo apt install -y lcov
      - run: melos generate
      - run: melos coverage
      - uses: codecov/codecov-action@v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  prompting-client-ui:
    runs-on: ubuntu-24.04
    steps:
      - uses: canonical/desktop-engineering/gh-actions/flutter/setup@e1069c189573b3525a60f54c5107ea3264f80805
      - run: melos generate
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang cmake gsettings-desktop-schemas libglib2.0-dev libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb
      - name: Run integration tests
        working-directory: flutter/apps/prompting_client_ui
        run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test
